---

- name: Migrate old db to new
  gather_facts: false
  hosts: localhost
  tasks:
    - name: include env vars
      include_vars: "vars/{{ datacenter }}.yaml"

    - name: include secret env vars
      include_vars: "vars/{{ datacenter }}-secrets.yaml"

    - name: Temporary directory for mysqldump
      ansible.builtin.tempfile:
        state: directory
        suffix: mysqldump
      register: dump_dir
      changed_when: False

    - name: Dump old database
      community.mysql.mysql_db:
        login_host: "{{ oldDb }}"
        login_user: superset
        login_password: "{{ dbPass }}"
        state: dump
        name: all
        target: "{{ dump_dir.path }}/dump.sql"

    - name: Restore to new database
      community.mysql.mysql_db:
        login_host: "{{ currentDb }}"
        login_user: superset
        login_password: "{{ dbPass }}"
        name: all
        state: import
        target: "{{ dump_dir.path }}/dump.sql"

    - name: Delete temporary directory
      ansible.builtin.file:
        state: absent
        path: "{{ dump_dir.path }}"
      changed_when: False
